### ISSUE TITLE
Remove jaxopt from pyproject requirements?

### ISSUE THREAD

**Issue by matthewcarbone** [ziatdinovmax/gpax#106]
https://github.com/ziatdinovmax/gpax/blob/2c69987b9e96b69b5dcf92c4d9b4fc118be19769/pyproject.toml#L30

It's not clear where this is used. There is a reference to it in [gpax/acquisition/optimize.py](https://github.com/ziatdinovmax/gpax/blob/2c69987b9e96b69b5dcf92c4d9b4fc118be19769/gpax/acquisition/optimize.py#L27). Is this one of those times where a dependency has an import that isn't strictly required?

**Comment by ziatdinovmax** [comment]
We need it for continuous acquisition functions. Currently this functionality is very limited (the assumption is that in experiment you always deal with discretized parameter space) and is outside of the primary package applications - hence, it is an optional dependency.
