### ISSUE TITLE
Notebook for Theory-informed data reconstruction and Bayesian optimization appears to be incorrect

### ISSUE THREAD

**Issue by matthewcarbone** [ziatdinovmax/gpax#30]
Looks like the linked notebook for this section in the README is wrong/incomplete. I don't see any of the example images from the readme in the notebook. I am very much interested in this example (on how to utilize the prior "theory" knowledge in the experiment). Thanks!

**Comment by ziatdinovmax** [comment]
I have fixed the URL so now it open the correct notebook - thanks for noticing!
