### ISSUE TITLE
We consider noisy observations of a discontinuous function...

### ISSUE THREAD

**Issue by jecampagne** [ziatdinovmax/gpax#6]
Hello,
I just read your excellent  [article](https://towardsdatascience.com/gaussian-process-first-step-towards-active-learning-in-physics-239a8b260579) and jump to your `gpax` lib. I already used `numpyro` for NUTS/SVI and a little practice for GP, and I was looking probably of what you are described in your `GP_sGP.ipynb`.  I would like to be sure that I have understand the use case developed at the end of your nb. 

Bellow I have display some data points and I know because of the process under the hood that there is a discontinuity at x close to (but not exactly) 0. Of course 1) I can fit a determinist parametrized function piecewise with an "linear" behaviour for x<x0 and a polynomial function for x>x0, 2) on a other hand I can use an RBF+noise GP but then I miss the discontinuity.

Do you think that your example is especially designed to keep up this discontinuity problem ?

![image](https://user-images.githubusercontent.com/20539759/155692712-44b04c5f-1285-4405-b254-fcf646604248.png)

Thanks

**Comment by sgbaird** [comment]
From a brief review of the README, a structured GP seems like a good use case for your problem.
