### ISSUE TITLE
Notebook hypoAL.ipynb appears to just be an older version of gpax_hypo.ipynb

### ISSUE THREAD

**Issue by matthewcarbone** [ziatdinovmax/gpax#61]
Consider just removing `hypoAL.ipynb`? They're not _quite_ the same but they're similar enough it seems.

**Comment by ziatdinovmax** [comment]
yup - the hypoAL.ipynb is redundant. Thanks for noticing!

**Comment by ziatdinovmax** [comment]
Close with #62
