### ISSUE TITLE
Unable to use gpu: might be a jax(or jaxlib) issue

### ISSUE THREAD

**Issue by utkarshp1161** [ziatdinovmax/gpax#63]
When I am running the gpax_vidkl_eels.ipynb  I am getting below warning:

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to CPU.

How to reproduce:

I created the python env using following steps:
conda create -n gpax_hae python==3.10
conda activate gpax_hae
pip install -e . (inside gpax repository) ------- this install most of the dependencies including jax and jaxlib
pip install jupyter
pip show atomai
pip install ipykernel

**Comment by ziatdinovmax** [comment]
@utkarshp1161 please try installing following these instructions: https://github.com/google/jax#instructions

**Comment by utkarshp1161** [comment]
It works now. Thanks.
