### ISSUE TITLE
Minor issue regarding importing sPM model

### ISSUE THREAD

**Issue by utkarshp1161** [ziatdinovmax/gpax#83]
Hi,

![image](https://github.com/ziatdinovmax/gpax/assets/52690126/5ca7f9d2-295e-48c9-b6ba-3f5fbfb98a00)

I installed gpax using : pip install gpax

Old notebooks have gpax.sPM

I guess below init.py should have sPM in .models

![image](https://github.com/ziatdinovmax/gpax/assets/52690126/da534bd7-d46b-4c43-9265-03a704031de0)

**Comment by ziatdinovmax** [comment]
Good catch. Can you please update the init file?

**Comment by utkarshp1161** [comment]
Sure.
